services:
  ethereum:
    image: ghcr.io/clarifiedlabs/foundry:stable
    entrypoint: anvil -p 8545 --host 0.0.0.0 --chain-id 31337 --silent
    ports:
      - "8545:8545"
  aztec-island:
    image: aztecprotocol/aztec:0.82.3
    ports:
      - "8080:8080"
    environment:
      FORCE_COLOR: 0
      LOG_LEVEL: info
      ETHEREUM_HOSTS: http://ethereum:8545
      PXE_PORT: 8080
      PORT: 8080
      L1_CHAIN_ID: 31337
      # DEPLOY_AZTEC_CONTRACTS_SALT: 1
      # ARCHIVER_VIEM_POLLING_INTERVAL_MS: 500
      # P2P_BLOCK_CHECK_INTERVAL_MS: 500
      # SEQ_TX_POLLING_INTERVAL_MS: 500
      # WS_BLOCK_CHECK_INTERVAL_MS: 500
      # ARCHIVER_POLLING_INTERVAL_MS: 500
      TEST_ACCOUNTS: "true"
      VERSION: latest
    depends_on:
      - ethereum
    command: node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start --sandbox
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/status" ]
      interval: 10s
      timeout: 10s
      retries: 5

#   command: aztec-sandbox-advance-blocks --pxe http://aztec:8080
#   depends_on:
#     aztec:
#       condition: service_healthy

  templerunner:
    build:
      context: ./templerunner
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - ethereum
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3001/status" ]
      interval: 10s
      timeout: 10s
      retries: 5
